### PR TITLE
added address, nomination note and more name fields

### PR DESCRIPTION
**Pull request by de-code**
Part of https://github.com/elifesciences/issues/issues/4773

I'm planning to add those additional fields.

### CODE REVIEW

**Comment by de-code** [comment]
I'm planning to get that applied to staging and then test the nifi flow in staging, before applying it to prod.

**Comment by giorgiosironi** [comment]
If this is merged `builder` could pick it up to apply it to any environment?

**Comment by de-code** [comment]
> If this is merged `builder` could pick it up to apply it to any environment?

Okay, maybe not ideal but shouldn't be a problem either. It would be adding columns that won't be used yet. The alternative would be to have a _development_ flow where I am free to change the schema myself.

**Comment by giorgiosironi** [comment]
> 
The alternative would be to have a _development_ flow where I am free to change the schema myself.

Goes hand-in-hand with the recent proposals _not to_ manage the schema from `builder` but from the application. `builder` creates an empty `dev` dataset, up to the most recent PR to drop tables, then recreate them or migrate them.

**Comment by de-code** [comment]
> Goes hand-in-hand with the recent proposals _not to_ manage the schema from `builder` but from the application. `builder` creates an empty `dev` dataset, up to the most recent PR to drop tables, then recreate them or migrate them.

How long do you think until we have that implemented? Ideally I would like this change to go in soonish.

**Comment by giorgiosironi** [comment]
It's easy for `builder` to just step back and manage an empty dataset; what's unclear is what this project should do to create and maintain the tables and their schemas in its place. Maybe https://github.com/elifesciences/data-pipeline-bigquery-views/ needs to be extended to do this?

**Comment by de-code** [comment]
> what's unclear is what this project should do to create and maintain the tables and their schemas in its place. Maybe https://github.com/elifesciences/data-pipeline-bigquery-views/ needs to be extended to do this?

I've raised a separate issue to keep the discussion and decision in one place.

**Comment by giorgiosironi** [comment]
So for this particular change, feel free to apply manually and `builder` will catch up (with some `terraform import` commands).

**Comment by de-code** [comment]
Successfully ran `bq update elife-data-pipeline:staging.380_datascience_early_career_researchers schemas/380_datascience_early_career_researchers.json`

Copied the new CSV file to test bucket (CSV filename must not have an additional suffix as that would be used as part of the name). Now debugging why it's failing...

**Comment by de-code** [comment]
Okay, that was me being stupid. I unintentionally renamed one field in my CSV.

In the NiFi log I was able to see the error:
```
2019-02-28 13:59:54,406 ERROR [Timer-Driven Process Thread-1] o.a.n.p.standard.ExecuteStreamCommand ExecuteStreamCommand[id=f177366c-a8cd-1cf6-3185-6346d1effc4c] Transferring flow file StandardFlowFileRecord[uuid=83f81c05-2bf6-4faa-ac39-08eb89df1d08,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1551362389999-91, container=default, section=91], offset=152773, length=442976],offset=0,name=ejp_query_tool_query_id_380_DataScience:_Early_Career_Researchers_2019_02_28_eLife.csv,Waiting on bqjob_r1ba7753491566a1c_00000169346779f1_1 ... (0s) Current status: DONE   
2019-02-28 13:59:54,420 ERROR [Timer-Driven Process Thread-9] o.a.nifi.processors.standard.LogMessage LogMessage[id=01681005-5f9e-18cc-6f83-f5eb9b65ea19] staging - ejp-csv-deposit - {"rc": "1", "stderr": "\rUpload complete.\rWaiting on bqjob_r1ba7753491566a1c_00000169346779f1_1 ... (0s) Current status: RUNNING\r                                                                                      \rWaiting on bqjob_r1ba7753491566a1c_00000169346779f1_1 ... (0s) Current status: DONE   ", "stdout": "\n\nBigQuery error in load operation: Error processing job\n'elife-data-pipeline:bqjob_r1ba7753491566a1c_00000169346779f1_1': Error while\nreading data, error message: JSON table encountered too many errors, giving up.\nRows: 1; errors: 1. Please look into the ", "filename": "ejp_query_tool_query_id_380_DataScience:_Early_Career_Researchers_2019_02_28_eLife.csv"}
```

Unfortunately that is truncated and missing the imported information (which I got from running it locally, see below):

```
... JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
Failure details:
- Error while reading data, error message: JSON parsing error in row
starting at position 0: No such field: person_id.
```

@lsh-0 it would be good if the error output wasn't truncated or allowed for more characters?

## Steps used to run it locally:

###  Setting up `virtualenv`

`./install.sh` failed due to missing `ensurepip` (if I remember correctly). I ran `virtualenv -p python3 venv` instead.

I found it a bit confusing to be within `scripts`. Maybe that could be at the root?

### Export to JSON

```
cat ejp_query_tool_query_id_380_DataScience\:_Early_Career_Researchers_2019_02_28_eLife.csv | ./venv/bin/python ejpcsv2json.py > ecr.json
```

### Upload to BQ

I can't use `load-file-to-bq.sh` because it is doing the login to `elife` - why? Isn't the server already running as `elife`?
EDIT: actually I see NiFi is running as `root`.

I was running it directly instead:

```bash
CLOUDSDK_CORE_PROJECT=elife-data-pipeline bq --location="US" load \
    --headless \
    --source_format=NEWLINE_DELIMITED_JSON \
    "staging.380_datascience_early_career_researchers" \
    "ecr.json"
```

(or at that point I actually used my `de_dev` dataset)

I've also tested it with an old CSV file, not having the additional fields and it imported fine.

@giorgiosironi would be good to get this merged and applied to the environments. After that I will amend the eJP query which produces the daily CSV (i.e. it would pick up the change tomorrow morning).

**Comment by giorgiosironi** [comment]
Is there anything that needs to happen prior to merge or should I go and run the `builder` tasks now?

**Comment by de-code** [comment]
No, nothing needs to happen before. I will do things after the schema has been applied.

**Comment by giorgiosironi** [comment]
Applied to `ci`, `staging`, `prod`.

**Comment by de-code** [comment]
Great, I made the query change.

**Comment by lsh-0** [comment]
> @lsh-0 it would be good if the error output wasn't truncated or allowed for more characters?

I'm not deliberately truncating anything, I'll investigate why that message is malformed.

**Comment by lsh-0** [comment]
(also, [as noted here](https://github.com/elifesciences/issues/issues/4779), this repository is dead, it just hasn't been archived yet. It was merged into this repo: https://github.com/elifesciences/data-pipeline-flow-support )

**Pull request merged**
